steps:
  - id: 'Build app'
    name: 'gcr.io/cloud-builders/mvn'
    args: [ 'install']

  - id: 'Run Checkstyle'
    name: 'gcr.io/cloud-builders/mvn'
    args: [ 'checkstyle:check']

options:
  logging: "CLOUD_LOGGING_ONLY"
