steps:
  - id: 'Build app'
    name: 'gcr.io/rugged-courier-444014-n0/maven-jdk21-builder'
    entrypoint: 'mvn'
    args: [ 'install' ]

  - id: 'Run Checkstyle'
    name: 'gcr.io/rugged-courier-444014-n0/maven-jdk21-builder'
    entrypoint: 'mvn'
    args: [ 'checkstyle:check']

  - id: 'Create image'
    name: 'gcr.io/rugged-courier-444014-n0/maven-jdk21-builder'
    entrypoint: 'mvn'
    args: [ 'jib:build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'spring-boot-web',
        '--image', 'europe-west2-docker.pkg.dev/rugged-courier-444014-n0/howells-docker-repository/spring-boot-web',
        '--platform', 'managed',
        '--region', 'europe-west2',
        '--allow-unauthenticated'
      ]

options:
  logging: "CLOUD_LOGGING_ONLY"
